version: "3"

services:
  fithesis3:
    image: fithesis3:latest
    build:
      context: .docker/fithesis
    environment:
      USER_NAME: fprochazka
      USER_UID: 1000
      USER_GID: 1000
    volumes:
      - ./:/doc
